<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita7028991dc8c017590dff76db6c1f59b
{
    public static $files = array (
        '950e8c5ec01dc90f029c243f73011631' => __DIR__ . '/..' . '/goaop/parser-reflection/src/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PhpParser\\' => 10,
        ),
        'G' => 
        array (
            'Go\\ParserReflection\\' => 20,
            'Go\\' => 3,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Annotations\\' => 28,
            'Demo\\Example\\' => 13,
            'Demo\\Aspect\\' => 12,
            'Demo\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'Go\\ParserReflection\\' => 
        array (
            0 => __DIR__ . '/..' . '/goaop/parser-reflection/src',
        ),
        'Go\\' => 
        array (
            0 => __DIR__ . '/..' . '/goaop/framework/src',
        ),
        'Doctrine\\Common\\Annotations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/annotations/lib/Doctrine/Common/Annotations',
        ),
        'Demo\\Example\\' => 
        array (
            0 => __DIR__ . '/../..' . '/demos/Demo/Example',
        ),
        'Demo\\Aspect\\' => 
        array (
            0 => __DIR__ . '/../..' . '/demos/Demo/Aspect',
        ),
        'Demo\\' => 
        array (
            0 => __DIR__ . '/../..' . '/demos/Demo',
        ),
    );

    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Dissect' => 
            array (
                0 => __DIR__ . '/..' . '/jakubledl/dissect/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita7028991dc8c017590dff76db6c1f59b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita7028991dc8c017590dff76db6c1f59b::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInita7028991dc8c017590dff76db6c1f59b::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
