<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'Go\\ParserReflection\\' => array($vendorDir . '/goaop/parser-reflection/src'),
    'Go\\' => array($vendorDir . '/goaop/framework/src'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Demo\\Example\\' => array($baseDir . '/demos/Demo/Example'),
    'Demo\\Aspect\\' => array($baseDir . '/demos/Demo/Aspect'),
    'Demo\\' => array($baseDir . '/demos/Demo'),
);
